---
- name: load role metas
  include_vars:
    file: "meta/main.yml"
- set_fact:
    role_supported_distributions: "{{ galaxy_info.platforms | json_query('[].name') | string | default ('unknow') }}"
- set_fact:
    role_supported_releases: "{{ (galaxy_info.platforms | selectattr('name', 'match', ansible_distribution) | list | first).versions | default ('unknow') | string }}"
- set_fact:
    ansible_distribution_release: "{{ ansible_distribution_version | string }}"
  when: ansible_distribution_release == ""
- block:
    - name: exclude unsupported distribution/release
      fail:
        msg: "HOST SKIPPED : {{ ansible_distribution }}/{{ ansible_distribution_release }} is not a supported distribution/release"
    - meta: end_host
  when: 
    ansible_distribution not in role_supported_distributions
    or
    ansible_distribution_release not in role_supported_releases


- block:
    - name: load variables
      include_vars:
        file: "{{ included_vars }}"
      with_first_found:
        - files:
            - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
            - "{{ ansible_distribution }}.yml"
            - "{{ ansible_os_family }}.yml"
            - "{{ ansible_system }}.yml"
            - "defaults.yml"
          paths:
            - "vars"
      loop_control:
        loop_var: included_vars
    - name: load tasks
      include_tasks:
        file: "{{ included_tasks }}"
      with_first_found:
        - files:
            - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
            - "{{ ansible_distribution }}.yml"
            - "{{ ansible_os_family }}.yml"
            - "{{ ansible_system }}.yml"
            - "defaults.yml"
          paths:
            - "tasks/distribution"
      loop_control:
        loop_var: included_tasks
