---
- name: install ntp package
  ansible.builtin.package:
    name: "{{ ntp_package }}"
    state: present


- name: install tzdata package
  ansible.builtin.package:
    name: "{{ ntp_tzdata_package }}"
    state: present


- name: set timezone
  ansible.builtin.template:
    src: "clock.j2"
    dest: "{{ ntp_timezone_file }}"
    mode: 0644
    owner: root
    group: root
    force: "yes"


- name: generate ntp configuration file
  ansible.builtin.template:
    src: "{{ ntp_config_file | basename }}.j2"
    dest: "{{ ntp_config_file }}"
    mode: 0644
    owner: root
    group: root
  notify: restart ntp
  when: ntp_manage_config | bool


- name: disable systemd-timesyncd
  ansible.builtin.service:
    name: systemd-timesyncd.service
    enabled: false
    state: stopped
  when:
    - ntp_enabled | bool
    - '"systemd-timesyncd.service" in services'


- name: enable and start ntp service
  ansible.builtin.service:
    name: "{{ ntp_daemon }}"
    state: started
    enabled: true
  when: ntp_enabled | bool


- name: disable and start ntp service
  ansible.builtin.service:
    name: "{{ ntp_daemon }}"
    state: stopped
    enabled: false
  when: not (ntp_enabled | bool)


# - name: disable systemd-timesyncd
#   ansible.builtin.service:
#     name: systemd-timesyncd.service
#     enabled: false
#     state: stopped
#   when:
#     - ntp_enabled | bool
#     - '"systemd-timesyncd.service" in services'
