---
- name: Install daemon packages for use {{ ntp_daemon_choice }}
  become: true
  when:
    - ntp_install_package | bool
  loop: "{{ ntp_daemon_conf[ntp_daemon_choice].ntp_daemon_install_package | flatten }}"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present

- name: Remove other daemons packages
  become: true
  when:
    - ntp_remove_package | bool
  loop: "{{ ntp_daemon_conf[ntp_daemon_choice].ntp_daemon_remove_package | flatten }}"
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent

- name: Install tzdata packages
  become: true
  when:
    - ntp_install_tzdata | bool
  loop: "{{ ntp_tzdata_package | flatten }}"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present

# - name: set timezone
#   ansible.builtin.copy:
#     dest: "{{ ntp_timezone_file }}"
#     content: "{{ ntp_timezone }}"
#     mode: 0644
#     owner: root
#     group: root

- name: Set timezone
  become: true
  community.general.timezone:
    name: "{{ ntp_timezone }}"
    # hwclock: UTC

- name: Create chrony confdir
  become: true
  when:
    - ntp_daemon_choice == "chrony"
  ansible.builtin.file:
    path: "{{ ntp_chrony_confdir }}"
    state: directory
    mode: "0644"
    owner: root
    group: root

- name: Create chrony envfile
  become: true
  when:
    - ntp_daemon_choice == "chrony"
    - ansible_os_family == "RedHat"
  ansible.builtin.copy:
    content: |
      # ansible_managed
      OPTIONS="-F 2 -f {{ ntp_daemon_conf[ntp_daemon_choice].ntp_daemon_config_file }}"
    dest: "{{ ntp_chrony_envfile }}"
    mode: "0644"
    owner: root
    group: root

- name: Create chrony envfile
  become: true
  when:
    - ntp_daemon_choice == "chrony"
    - ansible_os_family == "Debian"
  ansible.builtin.copy:
    content: |
      # ansible_managed
      DAEMON_OPTS="-F 2 -f {{ ntp_daemon_conf[ntp_daemon_choice].ntp_daemon_config_file }}"
    dest: "{{ ntp_chrony_envfile }}"
    mode: "0644"
    owner: root
    group: root

- name: Generate daemon configuration file for {{ ntp_daemon_choice }}
  become: true
  when:
    - ntp_manage_config | bool
  notify: restart selected daemon
  ansible.builtin.template:
    src: "{{ ntp_daemon_conf[ntp_daemon_choice].ntp_daemon_config_file | basename }}.j2"
    dest: "{{ ntp_daemon_conf[ntp_daemon_choice].ntp_daemon_config_file }}"
    mode: "0644"
    owner: root
    group: root

- name: Disable and stop others daemon services
  become: true
  when:
    - ntp_manage_services | bool
  loop: "{{ ntp_daemon_conf[ntp_daemon_choice].ntp_daemon_disable_service | flatten }}"
  ignore_errors: true
  # no_log: true
  # failed_when: false
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: false

# - name: enable and stop {{ ntp_daemon_choice }} daemon service
#   ansible.builtin.service:
#     name: "{{ item }}"
#     state: stopped
#     enabled: true
#   loop: "{{ ntp_daemon_conf[ntp_daemon_choice].ntp_daemon_enable_service | flatten }}"
#   when: ntp_manage_services | bool

- name: Systemd daemon-reload
  become: true
  when:
    - ansible_service_mgr == "systemd"
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart daemon service for {{ ntp_daemon_choice }}
  become: true
  when:
    - ntp_manage_services | bool
  loop: "{{ ntp_daemon_conf[ntp_daemon_choice].ntp_daemon_enable_service | flatten }}"
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
    enabled: true
